name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.python_version }}"
      
      - name: Lint PR Title
        run: python ci/lint_pr_title.py "${% raw %}{{ github.event.pull_request.title }}{% endraw %}"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{{ cookiecutter.python_version }}"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v5
      with:
        python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pre-commit
    
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    
    - name: Run tests
      run: |
        pytest tests/ --cov={{ cookiecutter.project_slug }} --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${% raw %}{{ secrets.CODECOV_TOKEN }}{% endraw %}
        file: ./coverage.xml
        flags: unittests 